#!/usr/bin/env bash

if [ -f "/sys/firmware/efi/fw_platform_size" ]; then
        pacman -S --needed efibootmgr
fi

pacman -S --needed \
        alsa-utils \
        base \
        base-devel \
        cmus \
        docker \
        feh \
        firefox \
        firefox-developer-edition \
        gimp \
        git \
        gpick \
        grub \
        htop \
        i3 \
        imagemagick \
        inkscape \
        keepassxc \
        kruler \
        libreoffice-fresh \
        linux \
        linux-firmware \
        lvm2 \
        man-db \
        man-pages \
        motion \
        mpv \
        networkmanager \
        openssh \
        pdftk \
        perl-image-exiftool \
        speedcrunch \
        sudo \
        texinfo \
        thunar \
        tldr \
        tmux \
        ttf-fira-code \
        vifm \
        vim \
        xdotool \
        xorg-server \
        zathura \
        zathura-pdf-mupdf \
        zathura-ps
